site_name: ''

# Repository
#repo_name: Slavik89/Atlasix-mkdocs-site
#repo_url: https://github.com/Slavik89/Atlasix-mkdocs-site

theme: 
  name: material
  logo: assets/images/atlasix_logo.jpg
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
  

  palette:

    - scheme: default
      primary: custom
      accent: deep orange
      toggle: 
        icon: material/weather-night
        name: Switch to light mode

    - scheme: slate
      primary: blue
      accent: deep orange
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    #- navigation.expand
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Knowledge base:
    - 'Start here': page2.md
    - 'End here': page3.md
  - Markdown Extentions: 
      - 'Admonitions': pages/markdown_extentions/admonitions.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - toc:
    # permalink: true



copyright: |
  &copy; 2024 
